---
- name: Install nginx
  dnf: name=nginx state=present

- name: Copy nginx configuration for pulp
  template:
    src: pulp_api_nginx.conf
    dest: /etc/nginx/site-enabled/pulp.conf
  notify: reload nginx
